# Generated by Django 4.1.5 on 2023-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InTransitTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
                ('city', models.TextField(null=True, verbose_name='cities')),
                ('date_start', models.DateTimeField(max_length=255, null=True, verbose_name='load_id')),
                ('date_end', models.DateTimeField(max_length=255, null=True, verbose_name='load_id')),
                ('drivers', models.TextField(verbose_name='drivers')),
            ],
            options={
                'verbose_name': 'In Transit Trip',
                'verbose_name_plural': 'In Transit Trips',
            },
        ),
        migrations.CreateModel(
            name='TripHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
                ('city', models.TextField(null=True, verbose_name='cities')),
                ('date_start', models.DateTimeField(max_length=255, null=True, verbose_name='load_id')),
                ('date_end', models.DateTimeField(max_length=255, null=True, verbose_name='load_id')),
                ('drivers', models.TextField(verbose_name='drivers')),
            ],
            options={
                'verbose_name': 'Trip History',
                'verbose_name_plural': 'Trip Histories',
            },
        ),
        migrations.CreateModel(
            name='UpcomingTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
                ('city', models.TextField(null=True, verbose_name='cities')),
                ('date_start', models.DateTimeField(max_length=255, verbose_name='load_id')),
                ('date_end', models.DateTimeField(max_length=255, verbose_name='load_id')),
                ('drivers', models.TextField(verbose_name='drivers')),
            ],
            options={
                'verbose_name': 'Upcoming Trip',
                'verbose_name_plural': 'Upcoming Trips',
            },
        ),
    ]
