# Generated by Django 4.1.5 on 2023-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intransittrips',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='intransittrips',
            name='date_start',
        ),
    ]
