# Generated by Django 4.1.5 on 2023-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_intransittrips_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransittrips',
            name='status',
            field=models.TextField(null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='triphistories',
            name='status',
            field=models.TextField(null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='upcomingtrips',
            name='status',
            field=models.TextField(null=True, verbose_name='status'),
        ),
    ]
