# Generated by Django 4.1.5 on 2023-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_intransittrips_date_end_intransittrips_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='triphistories',
            name='completed_or_not',
            field=models.TextField(null=True, verbose_name='completed'),
        ),
    ]
