# Generated by Django 4.1.5 on 2023-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_triphistories_completed_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triphistories',
            name='completed_or_not',
            field=models.TextField(default='Rejected/Canceled', null=True, verbose_name='completed'),
        ),
    ]
