# Generated by Django 4.1.5 on 2023-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_triphistories_completed_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransittrips',
            name='date_end',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
        migrations.AlterField(
            model_name='intransittrips',
            name='date_start',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
        migrations.AlterField(
            model_name='triphistories',
            name='date_end',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
        migrations.AlterField(
            model_name='triphistories',
            name='date_start',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
    ]
