# Generated by Django 4.1.5 on 2023-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_intransittrips_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtrips',
            name='date_end',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
        migrations.AddField(
            model_name='upcomingtrips',
            name='date_start',
            field=models.TextField(max_length=255, null=True, verbose_name='load_id'),
        ),
    ]
