# Generated by Django 4.1.5 on 2023-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_intransittrips_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intransittrips',
            name='city',
        ),
        migrations.RemoveField(
            model_name='triphistories',
            name='city',
        ),
        migrations.RemoveField(
            model_name='upcomingtrips',
            name='city',
        ),
        migrations.AddField(
            model_name='intransittrips',
            name='city_from',
            field=models.TextField(null=True, verbose_name='city from'),
        ),
        migrations.AddField(
            model_name='intransittrips',
            name='city_to',
            field=models.TextField(null=True, verbose_name='city to'),
        ),
        migrations.AddField(
            model_name='triphistories',
            name='city_from',
            field=models.TextField(null=True, verbose_name='city from'),
        ),
        migrations.AddField(
            model_name='triphistories',
            name='city_to',
            field=models.TextField(null=True, verbose_name='city to'),
        ),
        migrations.AddField(
            model_name='upcomingtrips',
            name='city_from',
            field=models.TextField(null=True, verbose_name='city from'),
        ),
        migrations.AddField(
            model_name='upcomingtrips',
            name='city_to',
            field=models.TextField(null=True, verbose_name='city to'),
        ),
    ]
