# Generated by Django 4.1.5 on 2023-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_intransittrips_city_remove_triphistories_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessagesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
            ],
            options={
                'verbose_name': 'Sent Message',
                'verbose_name_plural': 'Sent Messages',
            },
        ),
        migrations.CreateModel(
            name='SentMessagesTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
            ],
            options={
                'verbose_name': 'Sent Message',
                'verbose_name_plural': 'Sent Messages',
            },
        ),
        migrations.CreateModel(
            name='SentMessagesUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=255, verbose_name='load_id')),
            ],
            options={
                'verbose_name': 'Sent Message',
                'verbose_name_plural': 'Sent Messages',
            },
        ),
        migrations.RemoveField(
            model_name='triphistories',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='triphistories',
            name='date_start',
        ),
    ]
