# Generated by Django 4.1.5 on 2023-02-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sentmessageshistory_sentmessagestransit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_load_id', models.CharField(max_length=255, verbose_name='load_id')),
                ('Category', models.TextField(null=True, verbose_name='city from')),
                ('city_to', models.TextField(null=True, verbose_name='city to')),
                ('date_start', models.TextField(max_length=255, null=True, verbose_name='date')),
                ('due', models.TextField(verbose_name='why')),
                ('status', models.TextField(null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Trip History',
                'verbose_name_plural': 'Trip Histories',
            },
        ),
    ]
