# Generated by Django 4.1.5 on 2023-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notes_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.TextField(verbose_name='sent_note_load_id')),
            ],
        ),
    ]
