# Generated by Django 4.1.5 on 2023-02-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sentnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='trip',
            field=models.TextField(null=True, verbose_name='trip_id'),
        ),
    ]
